version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres112
    ports:
      - "5604:5432"
    environment:
      POSTGRES_DB: employee_claims_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: claim-backend
    ports:
      - "3604:3604"
    depends_on:
      - postgres

  employee-side-claim:
    build: ./employee-side-claim
    container_name: employee-side-claim
    ports:
      - "8608:80"
    depends_on:
      - backend

  hr-claim:
    build: ./hr-claim
    container_name: hr-claim
    ports:
      - "8009:80"
    depends_on:
      - backend

volumes:
  postgres-data:

